[tool.poetry]
name = "hh-projects"
version = "0.1.0"
description = ""
authors = ["Viktor Bochagov <vitekbochagov@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
